// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_TempLabel = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_HumLabel = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_ButtonAdd = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_ButtonSub = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Labelcnt = NULL;
// event funtions
void ui_event_ButtonAdd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ButtonAddFun(e);
    }
}

void ui_event_ButtonSub(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ButtonSubFun(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, 400);
    lv_obj_set_height(ui_Panel6, 200);
    lv_obj_set_x(ui_Panel6, -150);
    lv_obj_set_y(ui_Panel6, -112);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel5, 147);
    lv_obj_set_height(ui_Panel5, 74);
    lv_obj_set_x(ui_Panel5, -100);
    lv_obj_set_y(ui_Panel5, 50);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "当前湿度");
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel4, 147);
    lv_obj_set_height(ui_Panel4, 74);
    lv_obj_set_x(ui_Panel4, 98);
    lv_obj_set_y(ui_Panel4, -40);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempLabel = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "");
    lv_obj_set_style_text_align(ui_TempLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel3, 147);
    lv_obj_set_height(ui_Panel3, 74);
    lv_obj_set_x(ui_Panel3, 98);
    lv_obj_set_y(ui_Panel3, 50);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumLabel = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_HumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumLabel, 1);
    lv_obj_set_y(ui_HumLabel, 2);
    lv_obj_set_align(ui_HumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumLabel, "");
    lv_obj_set_style_text_align(ui_HumLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel2, 147);
    lv_obj_set_height(ui_Panel2, 74);
    lv_obj_set_x(ui_Panel2, -100);
    lv_obj_set_y(ui_Panel2, -40);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "当前温度");
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel7, 400);
    lv_obj_set_height(ui_Panel7, 200);
    lv_obj_set_x(ui_Panel7, -149);
    lv_obj_set_y(ui_Panel7, 96);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonAdd = lv_btn_create(ui_Panel7);
    lv_obj_set_width(ui_ButtonAdd, 100);
    lv_obj_set_height(ui_ButtonAdd, 50);
    lv_obj_set_x(ui_ButtonAdd, 109);
    lv_obj_set_y(ui_ButtonAdd, 50);
    lv_obj_set_align(ui_ButtonAdd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonAdd, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonAdd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_ButtonAdd);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "-");

    ui_ButtonSub = lv_btn_create(ui_Panel7);
    lv_obj_set_width(ui_ButtonSub, 100);
    lv_obj_set_height(ui_ButtonSub, 50);
    lv_obj_set_x(ui_ButtonSub, -106);
    lv_obj_set_y(ui_ButtonSub, 54);
    lv_obj_set_align(ui_ButtonSub, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSub, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSub, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_ButtonSub);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "+");

    ui_Panel8 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel8, 100);
    lv_obj_set_height(ui_Panel8, 50);
    lv_obj_set_x(ui_Panel8, 0);
    lv_obj_set_y(ui_Panel8, -29);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labelcnt = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Labelcnt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelcnt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labelcnt, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ButtonAdd, ui_event_ButtonAdd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSub, ui_event_ButtonSub, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Panel6 = NULL;
    ui_Panel5 = NULL;
    ui_Label5 = NULL;
    ui_Panel4 = NULL;
    ui_TempLabel = NULL;
    ui_Panel3 = NULL;
    ui_HumLabel = NULL;
    ui_Panel2 = NULL;
    ui_Label1 = NULL;
    ui_Panel7 = NULL;
    ui_ButtonAdd = NULL;
    ui_Label2 = NULL;
    ui_ButtonSub = NULL;
    ui_Label6 = NULL;
    ui_Panel8 = NULL;
    ui_Labelcnt = NULL;

}
