// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ButtonAddFun(lv_event_t * e)
{
	(void)e;
	// Your code here
}

void ButtinSubFun(lv_event_t * e)
{
	(void)e;
	// Your code here
}

void ButtonSubFun(lv_event_t * e)
{
	(void)e;
	// Your code here
}
