// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_HumLabel;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_alcLabel;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_acceLabely;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_acceLabelz;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_alarmLabel;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_stateLabel;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_acceLabelx;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_WeatherLabel;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_cityLabel;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_weatherDateDropdown;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_weekLabel;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_LabelF407;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_LabelF103;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

