// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_TempLabel = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_HumLabel = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_alcLabel = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_acceLabely = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_acceLabelz = NULL;
lv_obj_t * ui_Panel17 = NULL;
lv_obj_t * ui_alarmLabel = NULL;
lv_obj_t * ui_Panel14 = NULL;
lv_obj_t * ui_stateLabel = NULL;
lv_obj_t * ui_Panel16 = NULL;
lv_obj_t * ui_acceLabelx = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_WeatherLabel = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_cityLabel = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_weatherDateDropdown = NULL;
lv_obj_t * ui_Panel15 = NULL;
lv_obj_t * ui_weekLabel = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, 345);
    lv_obj_set_height(ui_Panel6, 231);
    lv_obj_set_x(ui_Panel6, -195);
    lv_obj_set_y(ui_Panel6, 93);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel5, 80);
    lv_obj_set_height(ui_Panel5, 35);
    lv_obj_set_x(ui_Panel5, -101);
    lv_obj_set_y(ui_Panel5, 8);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "当前湿度");
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel4, 155);
    lv_obj_set_height(ui_Panel4, 34);
    lv_obj_set_x(ui_Panel4, 27);
    lv_obj_set_y(ui_Panel4, -37);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempLabel = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "");
    lv_obj_set_style_text_align(ui_TempLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel3, 151);
    lv_obj_set_height(ui_Panel3, 35);
    lv_obj_set_x(ui_Panel3, 28);
    lv_obj_set_y(ui_Panel3, 7);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumLabel = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_HumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumLabel, 1);
    lv_obj_set_y(ui_HumLabel, 2);
    lv_obj_set_align(ui_HumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumLabel, "");
    lv_obj_set_style_text_align(ui_HumLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel2, 80);
    lv_obj_set_height(ui_Panel2, 39);
    lv_obj_set_x(ui_Panel2, -100);
    lv_obj_set_y(ui_Panel2, -38);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "当前温度");
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel1, 80);
    lv_obj_set_height(ui_Panel1, 34);
    lv_obj_set_x(ui_Panel1, -102);
    lv_obj_set_y(ui_Panel1, 51);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "酒精浓度");
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel8, 154);
    lv_obj_set_height(ui_Panel8, 34);
    lv_obj_set_x(ui_Panel8, 27);
    lv_obj_set_y(ui_Panel8, 51);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_alcLabel = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_alcLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alcLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_alcLabel, 1);
    lv_obj_set_y(ui_alcLabel, 2);
    lv_obj_set_align(ui_alcLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_alcLabel, "");
    lv_obj_set_style_text_align(ui_alcLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_alcLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -55);
    lv_obj_set_y(ui_Label3, -91);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "驾驶舱状态");
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel7, 493);
    lv_obj_set_height(ui_Panel7, 176);
    lv_obj_set_x(ui_Panel7, -135);
    lv_obj_set_y(ui_Panel7, -129);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -66);
    lv_obj_set_y(ui_Label4, -56);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "车辆姿态监测");
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel9, 100);
    lv_obj_set_height(ui_Panel9, 40);
    lv_obj_set_x(ui_Panel9, -3);
    lv_obj_set_y(ui_Panel9, -14);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_acceLabely = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_acceLabely, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_acceLabely, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_acceLabely, LV_ALIGN_CENTER);

    ui_Panel11 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel11, 100);
    lv_obj_set_height(ui_Panel11, 40);
    lv_obj_set_x(ui_Panel11, 162);
    lv_obj_set_y(ui_Panel11, -13);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_acceLabelz = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_acceLabelz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_acceLabelz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_acceLabelz, LV_ALIGN_CENTER);

    ui_Panel17 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel17, 100);
    lv_obj_set_height(ui_Panel17, 40);
    lv_obj_set_x(ui_Panel17, 108);
    lv_obj_set_y(ui_Panel17, 43);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_alarmLabel = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_alarmLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alarmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_alarmLabel, LV_ALIGN_CENTER);

    ui_Panel14 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel14, 100);
    lv_obj_set_height(ui_Panel14, 40);
    lv_obj_set_x(ui_Panel14, -82);
    lv_obj_set_y(ui_Panel14, 43);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_stateLabel = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_stateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_stateLabel, LV_ALIGN_CENTER);

    ui_Panel16 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel16, 100);
    lv_obj_set_height(ui_Panel16, 40);
    lv_obj_set_x(ui_Panel16, -154);
    lv_obj_set_y(ui_Panel16, -14);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_acceLabelx = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_acceLabelx, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_acceLabelx, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_acceLabelx, LV_ALIGN_CENTER);

    ui_Label11 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -223);
    lv_obj_set_y(ui_Label11, -13);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "X");

    ui_Label12 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -70);
    lv_obj_set_y(ui_Label12, -13);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Y");

    ui_Label13 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 94);
    lv_obj_set_y(ui_Label13, -14);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Z");

    ui_Label14 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Label14, -159);
    lv_obj_set_y(ui_Label14, 42);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "状态");
    lv_obj_set_style_text_align(ui_Label14, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 29);
    lv_obj_set_y(ui_Label15, 42);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "告警");
    lv_obj_set_style_text_align(ui_Label15, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel10, 325);
    lv_obj_set_height(ui_Panel10, 222);
    lv_obj_set_x(ui_Panel10, 155);
    lv_obj_set_y(ui_Panel10, 95);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherLabel = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_WeatherLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherLabel, -103);
    lv_obj_set_y(ui_WeatherLabel, -84);
    lv_obj_set_align(ui_WeatherLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherLabel, "天气预报");
    lv_obj_set_style_text_align(ui_WeatherLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_Panel10);
    lv_obj_set_width(ui_Panel12, 89);
    lv_obj_set_height(ui_Panel12, 40);
    lv_obj_set_x(ui_Panel12, -41);
    lv_obj_set_y(ui_Panel12, 16);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cityLabel = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_cityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cityLabel, -6);
    lv_obj_set_y(ui_cityLabel, -1);
    lv_obj_set_align(ui_cityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cityLabel, "city");
    lv_obj_set_style_text_font(ui_cityLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -115);
    lv_obj_set_y(ui_Label17, 13);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "城市");
    lv_obj_set_style_text_align(ui_Label17, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -102);
    lv_obj_set_y(ui_Label18, 59);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "天气状况");
    lv_obj_set_style_text_align(ui_Label18, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_Panel10);
    lv_obj_set_width(ui_Panel13, 196);
    lv_obj_set_height(ui_Panel13, 36);
    lv_obj_set_x(ui_Panel13, 40);
    lv_obj_set_y(ui_Panel13, 62);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 4);
    lv_obj_set_y(ui_Label20, 1);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -118);
    lv_obj_set_y(ui_Label19, -41);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "日期");
    lv_obj_set_style_text_align(ui_Label19, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherDateDropdown = lv_roller_create(ui_Panel10);
    lv_roller_set_options(ui_weatherDateDropdown, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_weatherDateDropdown, 50);
    lv_obj_set_width(ui_weatherDateDropdown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_weatherDateDropdown, -36);
    lv_obj_set_y(ui_weatherDateDropdown, -40);
    lv_obj_set_align(ui_weatherDateDropdown, LV_ALIGN_CENTER);

    ui_Panel15 = lv_obj_create(ui_Panel10);
    lv_obj_set_width(ui_Panel15, 98);
    lv_obj_set_height(ui_Panel15, 44);
    lv_obj_set_x(ui_Panel15, 78);
    lv_obj_set_y(ui_Panel15, -38);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weekLabel = lv_label_create(ui_Panel15);
    lv_obj_set_width(ui_weekLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weekLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weekLabel, -2);
    lv_obj_set_y(ui_weekLabel, 1);
    lv_obj_set_align(ui_weekLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weekLabel, "WEEK");
    lv_obj_set_style_text_font(ui_weekLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Panel6 = NULL;
    ui_Panel5 = NULL;
    ui_Label5 = NULL;
    ui_Panel4 = NULL;
    ui_TempLabel = NULL;
    ui_Panel3 = NULL;
    ui_HumLabel = NULL;
    ui_Panel2 = NULL;
    ui_Label1 = NULL;
    ui_Panel1 = NULL;
    ui_Label2 = NULL;
    ui_Panel8 = NULL;
    ui_alcLabel = NULL;
    ui_Label3 = NULL;
    ui_Panel7 = NULL;
    ui_Label4 = NULL;
    ui_Panel9 = NULL;
    ui_acceLabely = NULL;
    ui_Panel11 = NULL;
    ui_acceLabelz = NULL;
    ui_Panel17 = NULL;
    ui_alarmLabel = NULL;
    ui_Panel14 = NULL;
    ui_stateLabel = NULL;
    ui_Panel16 = NULL;
    ui_acceLabelx = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_Label15 = NULL;
    ui_Panel10 = NULL;
    ui_WeatherLabel = NULL;
    ui_Panel12 = NULL;
    ui_cityLabel = NULL;
    ui_Label17 = NULL;
    ui_Label18 = NULL;
    ui_Panel13 = NULL;
    ui_Label20 = NULL;
    ui_Label19 = NULL;
    ui_weatherDateDropdown = NULL;
    ui_Panel15 = NULL;
    ui_weekLabel = NULL;

}
